// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ViqV3THX0beHjRjcP_UePPJrj2qyu4A',
    appId: '1:443438025400:web:a531be10a00175f316424d',
    messagingSenderId: '443438025400',
    projectId: 'curelink-40d68',
    authDomain: 'curelink-40d68.firebaseapp.com',
    storageBucket: 'curelink-40d68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRay5CW81m32WJYk4Lzmrhb1WrHX5sG8E',
    appId: '1:443438025400:android:f889d880712bdcc216424d',
    messagingSenderId: '443438025400',
    projectId: 'curelink-40d68',
    storageBucket: 'curelink-40d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjxeYrU7QYDqpdHGl4B-c8RlJtbZnAWY',
    appId: '1:443438025400:ios:e2308bba70f69d0d16424d',
    messagingSenderId: '443438025400',
    projectId: 'curelink-40d68',
    storageBucket: 'curelink-40d68.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjxeYrU7QYDqpdHGl4B-c8RlJtbZnAWY',
    appId: '1:443438025400:ios:20064b73f9f519c116424d',
    messagingSenderId: '443438025400',
    projectId: 'curelink-40d68',
    storageBucket: 'curelink-40d68.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
